# Generated by Django 5.0.6 on 2024-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalentry',
            name='isAudited',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=100),
        ),
    ]
