# Generated by Django 5.0.6 on 2024-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0002_maternalentry_isaudited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='dob_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
