# Generated by Django 5.0.3 on 2024-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0003_alter_maternalentry_dob_unknown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maternalentry',
            name='other_place_of_anc',
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='occupation',
            field=models.CharField(choices=[('unemployed', 'Unemployed'), ('house wife', 'House wife'), ('farming', 'Farming'), ('trading', 'Trading'), ('artisan', 'Artisan(hairdresser, seamstress etc)'), ('civil/public servant', 'Civil/Public servant'), ('others (specify)', 'Others (Specify)')], default='unemployed', max_length=100),
        ),
    ]
