# Generated by Django 5.0.6 on 2024-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0004_remove_maternalentry_other_place_of_anc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='identified_risk_factors',
            field=models.TextField(choices=[('none', 'None'), ('hypertension', 'Hypertension'), ('sickle cell disease', 'Sickle Cell Disease'), ('previous caesarean section', 'Previous Caesarean Section'), ('diabetes mellitus', 'Diabetes Mellitus'), ('anaemia', 'Anaemia (HB < 11 g/dl; most current)'), ('previous PPH', 'Previous PPH'), ('others (specify)', 'Others (Specify)')], null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='other_interventions',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='transport_type',
            field=models.CharField(choices=[('ambulance', 'ambulance'), ('hospital vehicle', 'Hospital vehicle (not ambulance)'), ('public transport', 'Public Transport'), ('private transport', 'Private Transport'), ('others (specify)', 'Others (Specify)')], max_length=100, null=True),
        ),
    ]
