# Generated by Django 5.0.6 on 2024-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0006_maternalentry_declined_treatment_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternalentry',
            name='lack_of_transport_from_home_to_facility',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maternalentry',
            name='specify_lack_of_transport_from_home_to_facility',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='declined_treatment_admission',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='delay_in_seeking_help',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='hf_communication_breakdown',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='lack_of_transport_between_facility',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='lack_of_transport_from_home',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont know', 'Dont Know')], default='no', max_length=50, null=True),
        ),
    ]
