# Generated by Django 5.0.6 on 2024-05-17 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0008_maternalentry_potential_avoidable_factors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='time_treatment_started',
            field=models.TimeField(null=True),
        ),
    ]
