# Generated by Django 5.0.6 on 2024-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0009_alter_maternalentry_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='birth_weight',
            field=models.FloatField(null=True),
        ),
    ]
