# Generated by Django 5.0.6 on 2024-05-17 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0012_alter_maternalentry_place_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='date_autopsy_performed',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='date_of_death',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
