# Generated by Django 5.0.6 on 2024-06-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_entry', '0013_alter_maternalentry_date_autopsy_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternalentry',
            name='antenatal',
            field=models.TextField(choices=[('transfusion', 'Transfusion'), ('antibiotic therapy', 'Antibiotic Therapy'), ('external version', 'External version'), ('mag sulphate', 'Mag. Sulphate'), ('diazepam', 'Diazepam'), ('anti hypertensive', 'Anti Hypertensive'), ('hysterectomy', 'Hysterectomy')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='early_pregnancy',
            field=models.TextField(choices=[('evacuation', 'Evacuation'), ('antibiotic therapy', 'Antibiotic Therapy'), ('laparotomy', 'Laparotomy'), ('hysterectomy', 'Hysterectomy'), ('transfusion', 'Transfusion'), ('anti hypertensive', 'Anti Hypertensive')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='gestational_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='gravidity',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='intrapartum',
            field=models.TextField(choices=[('instrumental del', 'Instrumental del.'), ('antibiotic therapy', 'Antibiotic Therapy'), ('caesarian section', 'Caesarian section'), ('hysterectomy', 'Hysterectomy'), ('transfusion', 'Transfusion'), ('mag sulphate', 'Mag. Sulphate'), ('anti hypertensive', 'Anti Hypertensive'), ('diazepam', 'Diazepam')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='lessons_learnt',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='other_ethnicity',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='other_occupation',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='other_options',
            field=models.TextField(choices=[('anaesthesia-GA', 'Anaesthesia-GA'), ('epidural', 'Epidural'), ('spinal', 'Spinal'), ('local', 'Local'), ('invasive monitoring', 'Invasive monitoring'), ('anti hypertensive', 'Anti Hypertensive'), ('ICU ventilation', 'ICU ventilation')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='other_religion',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='parity',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='postpartum',
            field=models.TextField(choices=[('evacuation', 'Evacuation'), ('antibiotic therapy', 'Antibiotic Therapy'), ('laparotomy', 'Laparotomy'), ('hysterectomy', 'Hysterectomy'), ('transfusion', 'Transfusion'), ('manual removal of placenta', 'Manual removal of placenta'), ('anti hypertensive', 'Anti Hypertensive'), ('diazepam', 'Diazepam')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='recommendations',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='referral_from_where',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_declined_treatment_admission',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_delay_in_seeking_help',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_hf_communication_breakdown',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_lack_of_transport_between_facility',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_lack_of_transport_from_home',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maternalentry',
            name='specify_lack_of_transport_from_home_to_facility',
            field=models.CharField(default='none', max_length=250, null=True),
        ),
    ]
