# Generated by Django 5.0.6 on 2024-05-11 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_code', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility_creation.district')),
                ('facility_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facility_creation.region')),
            ],
        ),
    ]
