# Generated by Django 5.0.6 on 2024-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_creation', '0002_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
